### ISSUE TITLE
Каков смысл проекта

### ISSUE THREAD

**Issue by gdlbo** [CoffeeNappers/MacCoffee#1]
При отсутствии каких либо знаний по смалям, работе апи и в принципе модифицировании приложений тут валяется просто декомпиляция офвк без каких либо изменений

Выливается тогда простые и логичные вопросы: Как и зачем ты будешь реализовывать это чудо

**Comment by LenaTDDS** [comment]
> При отсутствии каких либо знаний по смалям, работе апи и в принципе модифицировании приложений тут валяется просто декомпиляция офвк без каких либо изменений
> 
> Выливается тогда простые и логичные вопросы: Как и зачем ты будешь реализовывать это чудо

Видимо кто-то плохо читал пост. На данный момент поднята версия апи и восстановлена работоспособность фотографий. Я стараюсь восстанавить и другие части, но из-за маленького кол-ва знаний у меня нет возможности делать это в одиночку. Если интересно -  можешь глянуть коммиты, чтобы увидеть сами изменения
